### PR TITLE
Command line interface

### PR DESCRIPTION
**Pull request by bobrown101**
This would be really helpful for me so I spent the last night or two writing one up.

I plan on testing this, and improving upon it much more.
My roadmap would be:
- Make it more linux-y as far as arguments go
- checks hosts file
- save the stream
- possibly display all available streams to status file so other programs can monitor them

Let me know what you think.

### CODE REVIEW

**Comment by bobrown101** [comment]
I forgot to mention, you can set the arguments in netbeans by going to:
Run -> Set project configuration -> Customize -> Arguments

For example here is the list of arguments to stream tonights devils game: 
-cli -league NHL -gameID 2017010036 -feedName HOME -cdn akc

**Comment by robotfood** [comment]
This looks really interesting, do you mind me asking what your use case would be for this?

I've been eyeing this project for a few days now and was thinking of "Mavenizing" it.

**Comment by bobrown101** [comment]
In my head it started out as "It would be cool if all devil's games could automatically start playing when they came on".  Then it morphed into adapting lazyman to be accessible through the cammand line and then writing a small script that automatically plays the games you want.

And then there was also the idea that if you created a command line interace, you would be able to write wrappers around it for any programming language you want, and that opens it up to a whole other realm of possibilities. 

As for maven I think that's a little much for the necessity right now.

**Comment by StevensNJD4** [comment]
Why not just make a standalone cli jar?

**Pull request closed without merging**
