### PR TITLE
GUI update

### PR DESCRIPTION
**Pull request by ransomts**
Here's the gui update for the latest version.
I made some choices here that are just how I think it should look, but obviously I can take suggestions. Plus I'm leaving edits from maintainers on so feel free to do whatever.

Thanks for your work and let's go canes!

### CODE REVIEW

**Comment by StevensNJD4** [comment]
Thanks! It's a bit tight on Linux and most likely OSX too. the play button doesn't show up. That's what I was having trouble with - keeping the same look across all OS's.

I really like it though

**Comment by ransomts** [comment]
Sure thing, I'll put in some extra margins no prob. What do you mean by the play button doesn't show up though? I can only test this on linux/windows so I suppose any OSX stuff I have to leave to others.

**Comment by StevensNJD4** [comment]
image
image

**Comment by ransomts** [comment]
ah okay gotcha, I can fix that

**Comment by StevensNJD4** [comment]
I am going to make this apart of Lazyman 3. Think you can pretty up the UI? Add graphics, etc

**Comment by ransomts** [comment]
neat, glad I can add something to the next version. I see you made a project todo for a new UI, I think that'd be a better place to hash out details than this pull. Maybe make a github organization to open up edits and such?

**Pull request merged**
